
# Deribit ingestion & aggregation config for Project X (v2: greeks + UTC + ISO expiry)
frequencies:
  snapshot_seconds: 60
  smile_seconds: 300
  instruments_refresh_s: 86400

universe:
  currencies: ["BTC", "ETH"]
  kind: "option"
  expired: false

storage:
  data_root: "./data"
  raw_dir: "raw/deribit"
  processed_dir: "processed/deribit"
  partitioning:
    raw: ["date", "underlying"]
    processed: ["date", "underlying"]
  parquet:
    compression: "zstd"
    use_dictionary: true
    row_group_size: 200000
    coerce_timestamps: "ms"

aggregation:
  price_field: "mid"
  iv_field: "iv"
  functions:
    mid: "mean"
    iv: "mean"
    delta: "mean"
    gamma: "mean"
    vega: "mean"
    theta: "mean"
    rho: "mean"

runtime:
  max_instruments: 10000
  request_sleep_ms: 120
